name: Generate badges

on:
  push:
    branches: [ main ]

jobs:
  generate-badges-on-badges-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Installing dependencies
        run: |
          cd app
          npm install

      - name: Tests
        run: |
          cd app
          npm run test:coverage

      - name: Switch to badges branch
        run: git switch badges

      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: '*'
          coverage-summary-path: app/coverage/coverage-summary.json
          no-commit: true
          target-branch: badges

      - name: Commit and push badges
        run: |
          cd badges
          if [[ `git status --porcelain *.svg` ]]; then
            git config --global user.name 'Groupings Project'
            git config --global user.email 'actions@noreply.its.hawaii.edu'
            git add .
            git commit -m "Autogenerated Jest badges"
            git push origin badges
          fi
